[master]
CLU ansible_host=192.168.30.20 ansible_user=davis ansible_ssh_private_key_file=~/.ssh/ansible

[node]
recognizer-1 ansible_host=192.168.30.21 ansible_user=davis ansible_ssh_private_key_file=~/.ssh/ansible
light-cycle-1 ansible_host=192.168.30.24 ansible_user=davis ansible_ssh_private_key_file=~/.ssh/ansible
rectifier-1 ansible_host=192.168.30.23 ansible_user=davis ansible_ssh_private_key_file=~/.ssh/ansible

# only required if proxmox_lxc_configure: true
# must contain all proxmox instances that have a master or worker node
# [proxmox]
# 192.168.30.43

[k3s_cluster:children]
master
node
